// lib/language-detection.ts
export type Language = 'en' | 'zh' | 'sr';

export interface LanguageContext {
  language: Language;
  setLanguage: (lang: Language) => void;
}

// Translations
export const translations = {
  en: {
    title: 'Open Superintelligence Lab',
    subtitle: '开放超级智能实验室',
    description: 'Advancing AI research and development through innovative approaches to artificial intelligence.',
    about: 'About',
    github: 'GitHub',
    toggleLanguage: '中文',
    projects: 'Research Projects',
    deepseekTitle: 'DeepSeek-V3.2-Exp Research',
    deepseekDescription: 'Open source research on DeepSeek Sparse Attention (DSA) and long-context efficiency improvements',
    deepseekStatus: 'Active Research',
    gptOssTitle: 'GPT-OSS Research',
    gptOssDescription: 'OpenAI\'s open-source MoE language models with advanced reasoning capabilities and safety features',
    gptOssStatus: 'Open Source',
    learnMore: 'Learn More',
    researchPath: 'Research Path',
    researchQuestions: 'Research Questions',
    contributions: 'How to Contribute',
    openSource: 'Open Source Research',
    deepseekResearchPath: 'Research Path',
    deepseekQuestions: 'Research Questions',
    deepseekContributions: 'How to Contribute',
    deepseekOpenSource: 'Open Source Research',
    gptOssResearchPath: 'Research Path',
    gptOssQuestions: 'Research Questions',
    gptOssContributions: 'How to Contribute',
    gptOssOpenSource: 'Open Source Research'
  },
  zh: {
    title: '开放超级智能实验室',
    subtitle: 'Open Superintelligence Lab',
    description: '通过创新的人工智能方法推进AI研究和开发。',
    about: '关于',
    github: 'GitHub',
    toggleLanguage: 'English',
    projects: '研究项目',
    deepseekTitle: 'DeepSeek-V3.2-Exp 研究',
    deepseekDescription: '关于DeepSeek稀疏注意力机制(DSA)和长上下文效率改进的开源研究',
    deepseekStatus: '活跃研究',
    gptOssTitle: 'GPT-OSS 研究',
    gptOssDescription: 'OpenAI的开源MoE语言模型，具有先进的推理能力和安全特性',
    gptOssStatus: '开源',
    learnMore: '了解更多',
    researchPath: '研究路径',
    researchQuestions: '研究问题',
    contributions: '如何贡献',
    openSource: '开源研究',
    deepseekResearchPath: '研究路径',
    deepseekQuestions: '研究问题',
    deepseekContributions: '如何贡献',
    deepseekOpenSource: '开源研究',
    gptOssResearchPath: '研究路径',
    gptOssQuestions: '研究问题',
    gptOssContributions: '如何贡献',
    gptOssOpenSource: '开源研究'
  },
  sr: {
    title: 'Laboratorija Otvorene Superinteligencije',
    subtitle: 'Open Superintelligence Lab',
    description: 'Unapređivanje istraživanja i razvoja AI kroz inovativne pristupe veštačkoj inteligenciji.',
    about: 'O nama',
    github: 'GitHub',
    toggleLanguage: 'Prevedi',
    projects: 'Istraživački Projekti',
    deepseekTitle: 'DeepSeek-V3.2-Exp Istraživanje',
    deepseekDescription: 'Istraživanje otvorenog koda o DeepSeek retkoj pažnji (DSA) i poboljšanjima efikasnosti dugog konteksta',
    deepseekStatus: 'Aktivno Istraživanje',
    gptOssTitle: 'GPT-OSS Istraživanje',
    gptOssDescription: 'OpenAI jezički modeli MoE otvorenog koda sa naprednim sposobnostima rasuđivanja i bezbednosnim karakteristikama',
    gptOssStatus: 'Otvoreni Kod',
    learnMore: 'Saznaj Više',
    researchPath: 'Istraživački Put',
    researchQuestions: 'Istraživačka Pitanja',
    contributions: 'Kako Doprineti',
    openSource: 'Istraživanje Otvorenog Koda',
    deepseekResearchPath: 'Istraživački Put',
    deepseekQuestions: 'Istraživačka Pitanja',
    deepseekContributions: 'Kako Doprineti',
    deepseekOpenSource: 'Istraživanje Otvorenog Koda',
    gptOssResearchPath: 'Istraživački Put',
    gptOssQuestions: 'Istraživačka Pitanja',
    gptOssContributions: 'Kako Doprineti',
    gptOssOpenSource: 'Istraživanje Otvorenog Koda'
  }
};
